### PR TITLE
[enchancement] Add firmware-upgrader image #138

### LINKED ISSUE #138: [module] Add firmware-upgrader module
https://github.com/openwisp/openwisp-firmware-upgrader

### PR DESCRIPTION
**Pull request by atb00ker**
Closes #138

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
@atb00ker I am not sure it's worth it to deploy the firmware upgrader in a dedicated container because it's not used nor called so often like the controller HTTP views or the monitoring views.

What about including it in the controller container? It should make sense.

**Comment by atb00ker** [comment]
> What about including it in the controller container? It should make sense.

Okay, Do you mean the dashboard image? Controller image is just the controller API! :smile:

**Comment by atb00ker** [comment]
> Okay, Do you mean the dashboard image? Controller image is just the controller API! smile

Added in the dashboard container.

**Comment by atb00ker** [comment]
Changing approach: 
```
- openwisp-dasboard             - Admin UI
- openwisp-radius               - Just radius API
- openwisp-devicemanager        - controller,  fw-upgrader, monitor, network-topology API
```

**Pull request merged**
