### PR TITLE
[nginx] Fix certbot cronjob handling Fixes #179

### LINKED ISSUE #179: [nginx] letsencrypt/certbot is missing the nginx plugin and the cronjob needs to be adjusted.
The current setup of the cronjob for certificate renewal is failing:
> /etc/nginx # crontab -l
> 0 3 * * 7 certbot renew &>> /etc/nginx/log/crontab.log

> certbot renew
> ...
> Attempting to renew cert (radius.xxx) from /etc/letsencrypt/renewal/radius.xxx.conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or IPv6.. Skipping.
> All renewal attempts failed. The following certs could not be renewed:
>  /etc/letsencrypt/live/controller.xxx/fullchain.pem (failure)
>  /etc/letsencrypt/live/dashboard.xxx/fullchain.pem (failure)
>  /etc/letsencrypt/live/radius.xxx/fullchain.pem (failure)

That's somewhat fixable by:
> apk add --no-cache certbot-nginx
> certbot --nginx renew
> ...
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
>
> Congratulations, all renewals succeeded. The following certs have been renewed:
>  /etc/letsencrypt/live/controller.xxx/fullchain.pem (success)
>  /etc/letsencrypt/live/dashboard.xxx/fullchain.pem (success)
>  /etc/letsencrypt/live/radius.xxx/fullchain.pem (success)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

I'll be adding a PR to address this later today.

### PR DESCRIPTION
**Pull request by tkaefer**
fixes #179

### CODE REVIEW

**Comment by tkaefer** [comment]
NOT align with the certbot-nginx plugin is the initial cert creation, see
```bash
function create_prod_certs {
    if [ ! -f /etc/letsencrypt/live/${DASHBOARD_DOMAIN}/privkey.pem ]; then
        certbot certonly --standalone --noninteractive --agree-tos \
                        --rsa-key-size 4096 \
                        --domain ${DASHBOARD_DOMAIN} \
                        --email ${CERT_ADMIN_EMAIL}
    fi
    if [ ! -f /etc/letsencrypt/live/${API_DOMAIN}/privkey.pem ]; then
        certbot certonly --standalone --noninteractive --agree-tos \
                        --rsa-key-size 4096 \
                        --domain ${API_DOMAIN} \
                        --email ${CERT_ADMIN_EMAIL}
    fi
    if [ ! -f /etc/letsencrypt/live/${RADIUS_DOMAIN}/privkey.pem ]; then
        certbot certonly --standalone --noninteractive --agree-tos \
                        --rsa-key-size 4096 \
                        --domain ${RADIUS_DOMAIN} \
                        --email ${CERT_ADMIN_EMAIL}
    fi
}```

IMHO it wouldn't fit in the current bootstrapping to adjust this to use the certbot-nginx plugin.
I'd rather have this separated from this PR.

**Comment by atb00ker** [comment]
Thanks, I'll test and merge it in a couple of days!

**Comment by tkaefer** [comment]
Yeah. Sorry about that. I've just came to know about that commit message issue.

**Comment by tkaefer** [comment]
@atb00ker fix amend and force pushed the commit message. Should be fine now.

**Comment by atb00ker** [comment]
FYI,

```
[nginx] Fix certbot cronjob handling #179

Closes #179
```

Will fix it! I know... so many rules!

**Comment by tkaefer** [comment]
@atb00ker Thanks for the hint. Hopefully It's okay now ;)

**Comment by atb00ker** [comment]
Sorry, I forgot to merge it before! :smile:

Thanks a lot @tkaefer ,

**Pull request merged**
