### PR TITLE
[improvements] Reformat strings to use f-strings #107

### LINKED ISSUE #107: [improvements] Use f-string for all strings
Check comment here: https://github.com/openwisp/docker-openwisp/pull/101#discussion_r382830175

### PR DESCRIPTION
**Pull request by Purhan**
Closes #107

### CODE REVIEW

**Comment by Purhan** [comment]
@atb00ker I'm sorry for closing the previous pull request, couldn't figure out how to squash properly and it ended up being a mess. Here is the new one. Please take a look. Thanks :smile:

**Review by atb00ker — COMMENTED** [review]
Okay, looks for merging.

A couple of lines got missed.
- `self.config['app_url'] + url` in `runtests.py`
- Couple of lines in `build/common/utils.py`

The rest seems good. Can you please check these? I'll merge this after that. :smile:

**Comment by atb00ker** [comment]
P.S: When you are done with making changes you can do `git commit --amend` to avoid making a  new commit and amending the current commit! :smile:

**Comment by atb00ker** [comment]
Thanks! :+1:

**Pull request merged**
