### PR TITLE
[change!] Changed the command to delete_old_radiusbatch_users #294

### LINKED ISSUE #294: [change] Update command name to delete_old_radiusbatch_users
Following the recent changes made in the https://github.com/openwisp/openwisp-radius/issues/496, the command name for deleting old users has been updated from delete_old_users to delete_old_radiusbatch_users for improved clarity and functionality.

As part of maintaining consistency across the OpenWISP project, it's imperative to update the command name in the docker-openwisp repository as well. This ensures coherence in naming conventions and functionality alignment

**Proposed Change:**
Change the name of the delete_old_users command to delete_old_radiusbatch_users. 

Update the documentation if required.

Similar to https://github.com/openwisp/ansible-openwisp2/issues/463
Refer https://github.com/search?q=repo%3Aopenwisp%2Fdocker-openwisp%20delete_old_users&type=code to know it's traces.

### PR DESCRIPTION
**Pull request by praptisharma28**
Updated the command. Related to openwisp/openwisp-radius#502 .This change ensures proper functionality and maintains consistency.

Closes #294

### CODE REVIEW

**Comment by praptisharma28** [comment]
Screenshot from 2024-03-09 20-12-50
Screenshot from 2024-03-09 20-12-50
Attached the screenshots too @nemesifier @pandafy

**Review by nemesifier — APPROVED** [review]
Thanks @praptisharma28 :+1:

**Comment by praptisharma28** [comment]
@nemesifier what corrections are needed to be done here now?

**Comment by nemesifier** [comment]
> @nemesifier what corrections are needed to be done here now?

Nothing here, just the build on master seems failing, we'll need to resolve that before merging.

**Comment by praptisharma28** [comment]
> @praptisharma28 From the initial impression it looks like a python dependency issue. Look a this line in the logs https://github.com/openwisp/docker-openwisp/pull/295/checks#step:6:1391

Yeah, u r right the error message indicates that the need for netaddr~=0.8 or netaddr~=0.8.0 is not fulfilled, but idk how to resolve it. @pandafy

**Review by nemesifier — APPROVED** [review]

**Pull request merged**
