### PR TITLE
[chores] Temporary version locking

### PR DESCRIPTION
**Pull request by atb00ker**
Did temporary version locking to avoid
the containers failing every once in a while
because of update in some other repository

### CODE REVIEW

**Comment by atb00ker** [comment]
> What about using git tags for those modules which have been released recently?

I thought, I'd do them all together when the other modules are released but sure, I'll check which ones are released and use git tags.

> Also, it could be interesting to make this configurable, because a developer may want to install a customized version (or a development version, or a fork) of one or more modules.

Can be done using build args, although I think the number of steps to make the changes would remain the same, so it wouldn't make it any easier for someone building their own images!

> I have on my todo list to release also the remaining ones (django-netjsonconfig, openwisp-controller, django-netjsongraph, openwisp-network-topology, django-freeradius, openwisp-radius).

That's great, waiting for it! :smile:

**Comment by atb00ker** [comment]
>> Also, it could be interesting to make this configurable, because a developer may want to install a customized version (or a development version, or a fork) of one or more modules.

> Can be done using build args, although I think the number of steps to make the changes would remain the same, so it wouldn't make it any easier for someone building their own images!

I found a problem with this. If I use variables in dockerfile, it doesn't cache the stage, i.e everytime the developer will make a change and build the image to see that change reflected, they'll have to wait for 2-3 minutes, which can be annoying if you fixing a bug, what do you think?

**Comment by nemesisdesign** [comment]
> I found a problem with this. If I use variables in dockerfile, it doesn't cache the stage, i.e everytime the developer will make a change and build the image to see that change reflected, they'll have to wait for 2-3 minutes, which can be annoying if you fixing a bug, what do you think?

@atb00ker without the possibility of installing variations of the official modules, one key goal of OpenWISP is not met: the possibility of reusing, extending and adapt the software to your own need.
I think this deserves to be moved into a separate issue and investigated further.

**Comment by atb00ker** [comment]
> OpenWISP is not met: the possibility of reusing, extending and adapt the software to your own need.
I think this deserves to be moved into a separate issue and investigated further

Okay, I'll open a issue for it and get back to it asap! :smile:

**Pull request merged**
